### ISSUE TITLE
 (RuntimeError)

### ISSUE THREAD

**Issue by rajeevkannav** [zeromq/rbzmq#18]
gem install zmq
Building native extensions.  This could take a while...
ERROR:  Error installing zmq:
    ERROR: Failed to build gem native extension.

```
    /home/rajeevkannav/.rvm/rubies/ruby-1.9.2-p290/bin/ruby extconf.rb
```

checking for zmq.h... no
checking for zmq.h in /opt/local/include,/usr/local/include,/usr/include... no
extconf.rb:36:in `<main>': Couldn't find zmq library. try setting --with-zmq-dir=<path> to tell me where it is. (RuntimeError)

Gem files will remain installed in /home/rajeevkannav/.rvm/gems/ruby-1.9.2-p290@ss2.0/gems/zmq-2.1.4 for inspection.
Results logged to /home/rajeevkannav/.rvm/gems/ruby-1.9.2-p290@ss2.0/gems/zmq-2.1.4/./gem_make.out

**Comment by bwbuchanan** [comment]
You need to install the ZeroMQ library.

**Comment by rajeevkannav** [comment]
How to install  ZeroMQ library. ??

**Comment by bwbuchanan** [comment]
http://lmgtfy.com/?q=how+do+i+install+zeromq
