### ISSUE TITLE
README.md should be README.rdoc

### ISSUE THREAD

**Issue by epitron** [zeromq/rbzmq#7]
Your README looks very wrong on github (https://github.com/zeromq/rbzmq) since its syntax is rdoc, not markdown.
# Fix

Rename `README.md` to `README.rdoc`

**Comment by bwbuchanan** [comment]
Fixed. Thanks!

**Comment by epitron** [comment]
No, thank YOU! :D

**Comment by DrummerHead** [comment]
Random trivia:

This is the first search result for 'rdoc vs md'
https://www.google.com/search?q=rdoc+vs+md&safe=off&pws=0&nfpr=1
